# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build + test + run for web

env:
  LOCAL_ASSETS_FOLDER: "assets"
  BUILD_DIR_RELEASE: "build/web"

on:
  push:
    branches: ["main", "develop"]

jobs:
  build:
    name: 🚀 Deploy website on push
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      security-events: write

    env:
      CONTAINER_IMAGE: ghcr.io/kataglyphis/kataglyphis_beschleuniger:latest
      FLUTTER_VERSION: 3.41.6
      FLUTTER_DIR: /workspace/flutter

    steps:
      - name: Free Disk Space on Host
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: 🚚 Get latest code
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull image
        run: |
          docker pull --platform "linux/amd64" "${{ env.CONTAINER_IMAGE }}"

      - name: Run container
        run: |
          docker run --rm --privileged \
            --platform "linux/amd64" \
            --volume "${GITHUB_WORKSPACE}:/workspace" \
            --workdir /workspace \
            "${{ env.CONTAINER_IMAGE }}" \
            bash /workspace/scripts/linux/ci/ci-container-run-web-linux.sh \
              --arch "x64" \
              --flutter-version "${{ env.FLUTTER_VERSION }}" \
              --flutter-dir "${{ env.FLUTTER_DIR }}" \
              --install-flutter true \
              --strict-checks false \
              --run-codeql false

      - name: Upload Web App Files for Deployment
        uses: actions/upload-artifact@v6.0.0
        with:
          name: gstreamer-ai-web-frontend
          path: ${{ env.BUILD_DIR_RELEASE }}/**
          if-no-files-found: error
